### ISSUE TITLE
Does this repo work on any visual inertial datasets?

### ISSUE THREAD

**Issue by alongqiyue** [pauvsi/pauvsi_vio#2]
Hi all:
    Does anybody knows this code working on visual inertial dataset(eg. Euroc dataset)?

**Comment by k-sheridan** [comment]
This software, in its current state is not finished. However, once finished it would work with any data set including IMU linear accelerations and angular rate measurements and monochrome images with their intrinsic matrix parameters. If there is distortion currently the program only accepts the opencv fisheye distortion model, but in the future it will also accept others.

In addition to the IMU measurements, you will have to setup a TF tree specifying where the IMU is with respect to the camera center.

This program will ultimately be put on the ros wiki and given instructions. When that happens it is ready to be used.

Sorry if this is a jumbled answer, I'm in class right now.
