### ISSUE TITLE
About bag file！

### ISSUE THREAD

**Issue by JinqiaoShi** [pauvsi/pauvsi_vio#3]
I am trying to have implementation the code. 
However, It's not working well for me with my bag file.
If you don't mind, I would like to get a bag file that working with the code,

**Comment by k-sheridan** [comment]
First of all this code is still a WIP. Right now it does a lot of stuff in the background and all you see as a result is the inertial motion estimation which drifts quadratically. 

When this code is finished all you have to do is publish a tf tree which describes the link between the base, camera, and imu. In addition to those an intrinsic matrix of the camera and its distortion parameters must be supplied through a camera message.
